# Generated by Django 2.0.7 on 2018-07-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=24)),
                ('parentesco', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'contactos',
                'managed': True,
            },
        ),
    ]
